# Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
# Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me.
#
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.orm import relationship

from data_collector.database import Base

# Location table
class Location(Base):
    __tablename__ = "locations"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False, index=True)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    forecast_url = Column(String(500), nullable=True)
    gridpoint_url = Column(String(500), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    weather_records = relationship("WeatherRecord", back_populates="location", cascade="all, delete-orphan")
    snow_records = relationship("SnowRecord", back_populates="location", cascade="all, delete-orphan")

# Weather record table
class WeatherRecord(Base):
    __tablename__ = "weather_records"

    id = Column(Integer, primary_key=True, index=True)
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=False, index=True)
    period_number = Column(Integer, nullable=False)
    period_name = Column(String(100), nullable=True)
    start_time = Column(DateTime, nullable=False, index=True)
    end_time = Column(DateTime, nullable=False)
    is_daytime = Column(Boolean, nullable=True)
    temperature = Column(Float, nullable=True)
    temperature_unit = Column(String(10), nullable=True)
    temperature_trend = Column(String(20), nullable=True)
    wind_speed = Column(String(50), nullable=True)
    wind_direction = Column(String(50), nullable=True)
    short_forecast = Column(String(200), nullable=True)
    detailed_forecast = Column(Text, nullable=True)
    fetched_at = Column(DateTime, default=datetime.utcnow)

    location = relationship("Location", back_populates="weather_records")

# Snow record table
class SnowRecord(Base):
    __tablename__ = "snow_records"

    id = Column(Integer, primary_key=True, index=True)
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=False, index=True)
    valid_time_start = Column(DateTime, nullable=False, index=True)
    valid_time_end = Column(DateTime, nullable=True)
    snowfall_amount = Column(Float, nullable=True)
    snowfall_unit = Column(String(20), nullable=True)
    snow_level = Column(Float, nullable=True)
    snow_level_unit = Column(String(20), nullable=True)
    fetched_at = Column(DateTime, default=datetime.utcnow)

    location = relationship("Location", back_populates="snow_records")
