# Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
# Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me.
#
# Event collaboration scheduler: triggers /fetch on startup and every 2 hours, notifies analyzer.
import logging
import time
import urllib.request
import urllib.error

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("scheduler")

API_FETCH_URL = "http://api:8000/fetch"
API_HEALTH_URL = "http://api:8000/health"
ANALYZER_NOTIFY_URL = "http://analyzer:8001/internal/notify"
FETCH_INTERVAL_SECONDS = 2 * 60 * 60
HEALTH_POLL_INTERVAL = 5
HEALTH_POLL_TIMEOUT = 120


def wait_for_api():
    # wait for the API to be up and get health
    elapsed = 0
    while elapsed < HEALTH_POLL_TIMEOUT:
        try:
            req = urllib.request.Request(API_HEALTH_URL)
            with urllib.request.urlopen(req, timeout=5) as r:
                if r.status == 200:
                    logger.info("API is up")
                    return
        except (urllib.error.URLError, OSError) as e:
            logger.info("Waiting for API... (%s)", e)
        time.sleep(HEALTH_POLL_INTERVAL)
        elapsed += HEALTH_POLL_INTERVAL
    raise RuntimeError("API did not become healthy in time")

# Helper function to trigger the fetch from the data collector
def trigger_fetch():
    req = urllib.request.Request(API_FETCH_URL, method="POST")
    with urllib.request.urlopen(req, timeout=300) as r:
        if r.status != 200:
            raise RuntimeError(f"Fetch returned {r.status}")
        logger.info("Fetch completed successfully")

# Helper function to refresh the data in the analyzer
def notify_subscribers():
    try:
        req = urllib.request.Request(ANALYZER_NOTIFY_URL, method="POST")
        with urllib.request.urlopen(req, timeout=10) as r:
            logger.info("Notified subscribers (weather_data_updated)")
    except Exception as e:
        logger.warning("Failed to notify subscribers: %s", e)


def main():
    logger.info("Scheduler starting")
    wait_for_api()

    def run_fetch_and_notify():
        try:
            trigger_fetch()
            notify_subscribers()
        except Exception as e:
            logger.error("Fetch or notify failed: %s", e)

    run_fetch_and_notify()

    while True:
        time.sleep(FETCH_INTERVAL_SECONDS)
        run_fetch_and_notify()


if __name__ == "__main__":
    main()
