# Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
# Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me.
#
# Pytest fixtures for tests. Creates seeded test data for integration tests.
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from data_collector.database import Base
from data_collector.models import Location, WeatherRecord, SnowRecord


@pytest.fixture
def test_engine():
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    return engine


@pytest.fixture
def db_session(test_engine):
    TestingSessionLocal = sessionmaker(
        autocommit=False, autoflush=False, bind=test_engine
    )
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.close()


def override_get_db(db_session_fixture):
    def _override():
        try:
            yield db_session_fixture
        finally:
            pass

    return _override


@pytest.fixture
def seeded_db(db_session):
    from datetime import datetime, timedelta

    loc = Location(
        name="Test Resort",
        latitude=39.5,
        longitude=-106.0,
    )
    db_session.add(loc)
    db_session.flush()

    now = datetime.utcnow()
    db_session.add(
        WeatherRecord(
            location_id=loc.id,
            period_number=1,
            start_time=now + timedelta(hours=1),
            end_time=now + timedelta(hours=6),
            is_daytime=True,
            temperature=25.0,
            wind_speed="5 mph",
            short_forecast="Sunny",
        )
    )
    db_session.add(
        SnowRecord(
            location_id=loc.id,
            valid_time_start=now - timedelta(hours=24),
            snowfall_amount=10.0,
        )
    )
    db_session.commit()

    yield db_session
