# Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
# Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me.
#
# Unit tests for the API endpoints.
import pytest
from fastapi.testclient import TestClient

from data_collector.database import get_db
from data_collector.main import app as data_collector_app
from data_analyzer.main import app as analyzer_app


def test_collector_health():
    client = TestClient(data_collector_app)
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_analyzer_health():
    client = TestClient(analyzer_app)
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_analyzer_internal_notify():
    client = TestClient(analyzer_app)
    response = client.post("/internal/notify")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"
    assert "subscribers" in data


def test_analyzer_scores_empty_db(db_session):
    def override_get_db():
        try:
            yield db_session
        finally:
            pass

    analyzer_app.dependency_overrides[get_db] = override_get_db
    try:
        client = TestClient(analyzer_app)
        response = client.get("/scores")
        assert response.status_code == 200
        data = response.json()
        assert "scores" in data
        assert data["scores"] == []
    finally:
        analyzer_app.dependency_overrides.pop(get_db, None)


def test_analyzer_scores_with_data(seeded_db):
    def override_get_db():
        try:
            yield seeded_db
        finally:
            pass

    analyzer_app.dependency_overrides[get_db] = override_get_db
    try:
        client = TestClient(analyzer_app)
        response = client.get("/scores")
        assert response.status_code == 200
        data = response.json()
        assert "scores" in data
        assert len(data["scores"]) >= 1
        top = data["scores"][0]
        assert "resort_name" in top
        assert "score" in top
        assert top["resort_name"] == "Test Resort"
        assert 0 <= top["score"] <= 100
    finally:
        analyzer_app.dependency_overrides.pop(get_db, None)


def test_analyzer_scores_include_details(seeded_db):
    def override_get_db():
        try:
            yield seeded_db
        finally:
            pass

    analyzer_app.dependency_overrides[get_db] = override_get_db
    try:
        client = TestClient(analyzer_app)
        response = client.get("/scores?include_details=true")
        assert response.status_code == 200
        data = response.json()
        assert len(data["scores"]) >= 1
        assert data["scores"][0]["details"] is not None
    finally:
        analyzer_app.dependency_overrides.pop(get_db, None)


def test_analyzer_resort_score_by_name(seeded_db):
    def override_get_db():
        try:
            yield seeded_db
        finally:
            pass

    analyzer_app.dependency_overrides[get_db] = override_get_db
    try:
        client = TestClient(analyzer_app)
        response = client.get("/scores/Test%20Resort")
        assert response.status_code == 200
        data = response.json()
        assert data["resort_name"] == "Test Resort"
        assert "score" in data
    finally:
        analyzer_app.dependency_overrides.pop(get_db, None)


def test_analyzer_resort_score_not_found(db_session):
    def override_get_db():
        try:
            yield db_session
        finally:
            pass

    analyzer_app.dependency_overrides[get_db] = override_get_db
    try:
        client = TestClient(analyzer_app)
        response = client.get("/scores/NonexistentResort")
        assert response.status_code == 404
    finally:
        analyzer_app.dependency_overrides.pop(get_db, None)
