# Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
# Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me.
#
# Unit tests for the data analyzer.
from datetime import datetime, timedelta
from unittest.mock import patch

import pytest

from data_collector.models import WeatherRecord, SnowRecord
from data_analyzer.main import (
    _conditions_score,
    _meters_to_inches,
    _parse_wind_mph,
    _snow_score,
    _snowfall_to_inches,
    _temperature_score,
    _wind_score,
    compute_ski_score,
)

def test_parse_wind_mph_simple():
    assert _parse_wind_mph("5 mph") == 5.0
    assert _parse_wind_mph("15 mph") == 15.0


def test_parse_wind_mph_range():
    assert _parse_wind_mph("0 to 10 mph") == 5.0
    assert _parse_wind_mph("10 to 20 mph") == 15.0


def test_parse_wind_mph_none_or_empty():
    assert _parse_wind_mph(None) == 0.0
    assert _parse_wind_mph("") == 0.0

def test_meters_to_inches():
    assert _meters_to_inches(1.0) == pytest.approx(39.37, rel=0.01)
    assert _meters_to_inches(0.01) == pytest.approx(0.3937, rel=0.01)


def test_meters_to_inches_none():
    assert _meters_to_inches(None) == 0.0

def test_snowfall_to_inches_cm():
    assert _snowfall_to_inches(10.0, "wmoUnit:cm") == pytest.approx(3.937, rel=0.01)
    assert _snowfall_to_inches(23.0, "wmoUnit:cm") == pytest.approx(9.06, rel=0.01)
    assert _snowfall_to_inches(23.0, "wmoUnit:m") == pytest.approx(9.06, rel=0.01) 


def test_temperature_score_ideal():
    score, note = _temperature_score(22)
    assert score >= 19  
    assert "22" in note


def test_temperature_score_too_cold():
    score, note = _temperature_score(-20)
    assert score < 15
    assert "-20" in note


def test_temperature_score_too_warm():
    score, note = _temperature_score(50)
    assert score < 15
    assert "50" in note


def test_temperature_score_none():
    score, note = _temperature_score(None)
    assert score == 0.0
    assert "no data" in note


def test_temperature_score_bounds():
    score, _ = _temperature_score(15)
    assert 0 <= score <= 25
    score, _ = _temperature_score(30)
    assert 0 <= score <= 25


def test_wind_score_low():
    score, note = _wind_score(3)
    assert score == 25
    assert "3.0" in note


def test_wind_score_high():
    score, note = _wind_score(30)
    assert score < 10
    assert "30.0" in note


def test_wind_score_bounds():
    score, _ = _wind_score(0)
    assert 0 <= score <= 25
    score, _ = _wind_score(50)
    assert 0 <= score <= 25


def test_snow_score_no_snow():
    score, note = _snow_score(0, 0, False)
    assert score == 10
    assert "0.0" in note


def test_snow_score_with_recent():
    score, _ = _snow_score(4.0, 0, False)
    assert score > 10
    assert score <= 25


def test_snow_score_with_forecast_snow():
    score, _ = _snow_score(0, 0, True)
    assert score == 15


def test_snow_score_all_factors():
    score, _ = _snow_score(2.0, 1.0, True)
    assert score >= 15
    assert score <= 25

def test_conditions_score_snow():
    score, note = _conditions_score("Chance of snow showers")
    assert score == 22
    assert "snow" in note


def test_conditions_score_rain():
    score, note = _conditions_score("Rain likely")
    assert score == 3
    assert "rain" in note


def test_conditions_score_sunny():
    score, note = _conditions_score("Sunny")
    assert score == 15
    assert "clear" in note or "sunny" in note


def test_conditions_score_none():
    score, note = _conditions_score(None)
    assert score == 12.5
    assert "no data" in note


def test_conditions_score_mixed():
    score, _ = _conditions_score("Partly cloudy")
    assert score == 12.5


def _make_weather_record(
    temperature=25.0,
    wind_speed="5 mph",
    short_forecast="Sunny",
    start_offset_hours=1,
    is_daytime=True,
):
    now = datetime.utcnow()
    return WeatherRecord(
        location_id=1,
        period_number=1,
        start_time=now + timedelta(hours=start_offset_hours),
        end_time=now + timedelta(hours=start_offset_hours + 6),
        is_daytime=is_daytime,
        temperature=temperature,
        wind_speed=wind_speed,
        short_forecast=short_forecast,
    )


def _make_snow_record(valid_offset_hours=0, snowfall_amount=0.01):
    now = datetime.utcnow()
    return SnowRecord(
        location_id=1,
        valid_time_start=now + timedelta(hours=valid_offset_hours),
        snowfall_amount=snowfall_amount,
    )


def test_compute_ski_score_returns_valid_score():
    weather = [_make_weather_record()]
    snow = []
    score, details = compute_ski_score(weather, snow, include_details=True)
    assert 0 <= score <= 100
    assert details is not None


def test_compute_ski_score_returns_details_when_requested():
    weather = [_make_weather_record()]
    snow = []
    score, details = compute_ski_score(weather, snow, include_details=True)
    assert details is not None
    assert hasattr(details, "temperature_score")
    assert hasattr(details, "wind_score")
    assert hasattr(details, "snow_score")
    assert hasattr(details, "conditions_score")
    assert hasattr(details, "factors")


def test_compute_ski_score_no_details_when_requested():
    weather = [_make_weather_record()]
    snow = []
    score, details = compute_ski_score(weather, snow, include_details=False)
    assert details is None
    assert 0 <= score <= 100


def test_compute_ski_score_empty_records():
    score, details = compute_ski_score([], [], include_details=True)
    assert 0 <= score <= 100
    assert details is not None
