# Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
# Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me.
#
# Integration test using the seeded database to check scores.
from fastapi.testclient import TestClient

from data_collector.database import get_db
from data_analyzer.main import app as analyzer_app


def test_seeded_db_produces_analyzer_scores(seeded_db):
    def override_get_db():
        try:
            yield seeded_db
        finally:
            pass

    analyzer_app.dependency_overrides[get_db] = override_get_db
    try:
        client = TestClient(analyzer_app)
        response = client.get("/scores?include_details=true")
        assert response.status_code == 200
        data = response.json()
        assert "scores" in data
        assert len(data["scores"]) >= 1
        top = data["scores"][0]
        assert top["resort_name"] == "Test Resort"
        assert 0 <= top["score"] <= 100
        assert top["details"] is not None
        assert "temperature" in top["details"]["factors"]
        assert "wind" in top["details"]["factors"]
    finally:
        analyzer_app.dependency_overrides.pop(get_db, None)
