/* Cursor. (2026). Cursor Composer (Version 1.5) [Large language model]. https://cursor.com/
   Citation applies to: Lines 1-final. Generated by Cursor; revised and integrated by me. */
import { useCallback, useEffect, useState } from "react";

interface SkiScoreDetail {
  temperature_score: number;
  wind_score: number;
  snow_score: number;
  conditions_score: number;
  factors: {
    temperature?: string;
    wind?: string;
    snow?: string;
    conditions?: string;
  };
}

interface SkiScoreResult {
  resort_name: string;
  score: number;
  details: SkiScoreDetail | null;
}

interface SkiScoresResponse {
  scores: SkiScoreResult[];
}

function getApiBase(): string {
  return import.meta.env.DEV
    ? "/api"
    : import.meta.env.VITE_API_URL || "http://localhost:8001";
}

function App() {
  const [scores, setScores] = useState<SkiScoreResult[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lookupInput, setLookupInput] = useState("");
  const [lookupResult, setLookupResult] = useState<SkiScoreResult | null>(null);
  const [lookupError, setLookupError] = useState<string | null>(null);

  const fetchResortScore = useCallback(
    async (resortName: string) => {
      setLookupError(null);
      setLookupResult(null);
      const apiBase = getApiBase();
      try {
        const encoded = encodeURIComponent(resortName);
        const res = await fetch(`${apiBase}/scores/${encoded}?include_details=true`);
        if (!res.ok) {
          const err = await res.json().catch(() => ({}));
          throw new Error(err.detail ?? `Resort not found: ${resortName}`);
        }
        const data: SkiScoreResult = await res.json();
        setLookupResult(data);
      } catch (err) {
        setLookupError(err instanceof Error ? err.message : "Could not load resort");
      }
    },
    []
  );

  const fetchScores = useCallback(async () => {
    const apiBase = getApiBase();
    try {
      const res = await fetch(`${apiBase}/scores?include_details=true`);
      if (!res.ok) throw new Error(`Failed to load scores: ${res.status}`);
      const data: SkiScoresResponse = await res.json();
      setScores(data.scores);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchScores();
  }, [fetchScores]);

  // Event collaboration: subscribe to SSE for "weather_data_updated" notifications
  useEffect(() => {
    const apiBase = getApiBase();
    const eventsUrl = `${apiBase}/events`;
    const eventSource = new EventSource(eventsUrl);

    eventSource.onmessage = (e) => {
      try {
        const data = JSON.parse(e.data);
        if (data?.event === "weather_data_updated") {
          fetchScores();
        }
      } catch {
        // Non-JSON or unexpected format; refetch anyway
        fetchScores();
      }
    };

    eventSource.onerror = () => {
      eventSource.close();
      // Reconnect after delay (EventSource auto-reconnects, but close then recreate can help)
    };

    return () => eventSource.close();
  }, [fetchScores]);

  if (loading) {
    return (
      <div className="container">
        <div className="loading">Loading ski scores…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container">
        <div className="error">
          <h2>Could not load data</h2>
          <p>{error}</p>
          <p className="hint">
            Make sure the analyzer is running at http://localhost:8001
          </p>
        </div>
      </div>
    );
  }

  const top3 = scores.slice(0, 3);
  const topResort = top3[0];

  return (
    <div className="container">
      <header>
        <h1>Colorado Ski Score</h1>
        <p className="subtitle">Best resorts right now</p>
      </header>

      <section className="top-three">
        <h2>Top 3 resorts</h2>
        <ol className="resort-list">
          {top3.map((r, i) => (
            <li
              key={r.resort_name}
              className={i === 0 ? "resort-item top" : "resort-item"}
            >
              <span className="rank">#{i + 1}</span>
              <span className="name">{r.resort_name}</span>
              <span className="score">{r.score.toFixed(1)}</span>
            </li>
          ))}
        </ol>
      </section>

      {topResort?.details && (
        <section className="detail-report">
          <h2>
            Detailed report — <em>{topResort.resort_name}</em>
          </h2>
          <div className="detail-grid">
            <div className="detail-card">
              <h3>Temperature</h3>
              <p className="value">{topResort.details.factors.temperature ?? "—"}</p>
              <p className="sub">Score: {topResort.details.temperature_score}/25</p>
            </div>
            <div className="detail-card">
              <h3>Wind</h3>
              <p className="value">{topResort.details.factors.wind ?? "—"}</p>
              <p className="sub">Score: {topResort.details.wind_score}/25</p>
            </div>
            <div className="detail-card">
              <h3>Conditions</h3>
              <p className="value">{topResort.details.factors.conditions ?? "—"}</p>
              <p className="sub">Score: {topResort.details.conditions_score}/25</p>
            </div>
            <div className="detail-card">
              <h3>Snow</h3>
              <p className="value">{topResort.details.factors.snow ?? "—"}</p>
              <p className="sub">Score: {topResort.details.snow_score}/25</p>
            </div>
          </div>
        </section>
      )}

      <section className="resort-lookup">
        <h2>Look up a resort</h2>
        <form
          className="lookup-form"
          onSubmit={(e) => {
            e.preventDefault();
            const input = e.currentTarget.querySelector<HTMLInputElement>('input[name="resort"]');
            const name = input?.value?.trim();
            if (name) fetchResortScore(name);
          }}
        >
          <input
            type="text"
            name="resort"
            placeholder="e.g. Aspen, Vail, Breckenridge"
            value={lookupInput}
            onChange={(e) => setLookupInput(e.target.value)}
            aria-label="Resort name"
          />
          <button type="submit">Get score</button>
        </form>
        {(lookupResult || lookupError) && (
          <div className={`lookup-result ${lookupError ? "error" : ""}`}>
            {lookupError ? (
              <p>{lookupError}</p>
            ) : lookupResult ? (
              <>
                <p className="lookup-resort">{lookupResult.resort_name}</p>
                <p className="lookup-score">Score: {lookupResult.score.toFixed(1)}</p>
                {lookupResult.details && (
                  <div className="lookup-details">
                    <p>Temperature: {lookupResult.details.factors.temperature}</p>
                    <p>Wind: {lookupResult.details.factors.wind}</p>
                    <p>Snow: {lookupResult.details.factors.snow}</p>
                    <p>Conditions: {lookupResult.details.factors.conditions}</p>
                  </div>
                )}
              </>
            ) : null}
          </div>
        )}
      </section>

      <footer>
        <p>Data from NWS • Auto-updates when weather data is fetched</p>
      </footer>
    </div>
  );
}

export default App;
